//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHands_FILSOV.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilsovWorldSkillsDemoEntities : DbContext
    {
        public FilsovWorldSkillsDemoEntities()
            : base("name=FilsovWorldSkillsDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<MaterialsSupliers> MaterialsSupliers { get; set; }
        public virtual DbSet<Supliers> Supliers { get; set; }
        public virtual DbSet<TypeMaterials> TypeMaterials { get; set; }
        public virtual DbSet<TypeSupliers> TypeSupliers { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
