//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHands_FILSOV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsSupliers
    {
        public int idMaterialSuplier { get; set; }
        public int idMaterial { get; set; }
        public int idSupliers { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Supliers Supliers { get; set; }
    }
}
