//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHands_FILSOV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialsSupliers = new HashSet<MaterialsSupliers>();
        }
    
        public int idMaterials { get; set; }
        public string Name { get; set; }
        public int idTypeMaterials { get; set; }
        public string Image { get; set; }
        public decimal Cost { get; set; }
        public int QuantityOnStorage { get; set; }
        public int MinimumQuantity { get; set; }
        public int QuntityInPack { get; set; }
        public int idUnit { get; set; }
    
        public virtual TypeMaterials TypeMaterials { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsSupliers> MaterialsSupliers { get; set; }
    }
}
