//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothersForHands_FILSOV.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supliers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supliers()
        {
            this.MaterialsSupliers = new HashSet<MaterialsSupliers>();
        }
    
        public int idSuplier { get; set; }
        public string NameSuplier { get; set; }
        public int idTypeSuplier { get; set; }
        public string INN { get; set; }
        public int RatingOfQuality { get; set; }
        public System.DateTime DateStart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsSupliers> MaterialsSupliers { get; set; }
        public virtual TypeSupliers TypeSupliers { get; set; }
    }
}
